/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#7f2448",
        "surface-variant": "#e0e4da",
        "primary-fixed-dim": "#88d982",
        "on-primary-container": "#cbffc2",
        "error-container": "#ffdad6",
        "inverse-primary": "#88d982",
        "on-surface": "#181d17",
        "secondary-fixed": "#ffdbcf",
        "error": "#ba1a1a",
        "tertiary": "#923357",
        "inverse-surface": "#2d322b",
        "tertiary-container": "#b14b6f",
        "on-secondary-container": "#795548",
        "surface-bright": "#f7fbf0",
        "on-background": "#181d17",
        "on-primary-fixed-variant": "#005312",
        "on-primary-fixed": "#002204",
        "on-surface-variant": "#40493d",
        "surface-container-high": "#e5eadf",
        "primary-fixed": "#a3f69c",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ebbcac",
        "surface": "#f7fbf0",
        "tertiary-fixed-dim": "#ffb1c7",
        "on-secondary": "#ffffff",
        "surface-dim": "#d7dbd2",
        "on-error": "#ffffff",
        "surface-container-low": "#f1f5eb",
        "on-error-container": "#93000a",
        "secondary-container": "#fdcdbc",
        "tertiary-fixed": "#ffd9e2",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eef2e8",
        "on-secondary-fixed-variant": "#603f33",
        "background": "#f7fbf0",
        "secondary": "#7a5649",
        "primary": "#0d631b",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#bfcaba",
        "on-tertiary-container": "#ffedf0",
        "on-secondary-fixed": "#2e150b",
        "outline": "#707a6c",
        "surface-container-highest": "#e0e4da",
        "on-tertiary-fixed": "#3f001c",
        "primary-container": "#2e7d32",
        "surface-container": "#ebefe5",
        "surface-tint": "#1b6d24"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "xl": "32px",
        "gutter": "16px",
        "sm": "8px",
        "container-margin": "24px",
        "md": "16px",
        "lg": "24px",
        "base": "4px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
